### ISSUE TITLE
[TEST] InGame 관련 커서 부분 Issue

### ISSUE THREAD

**Issue by pyunghun** [MetaAir2023/WebRPG#107]
## Description
테스트에 관한 이슈 템플릿입니다.

예시)
### 테스트할 클래스 :  인게임 커서 적용 부분 확인
  

---

## 주요 테스트 내용

* 인게임 플레이 중 back, elemetalType 버튼 cover 시 마우스 커서 미적용 이슈
---

## TODO
- [x]  html 파일에서 cursor 에 대한 주소값 적용 확인을 한다.
- [x] 주소값 확인 후 Ingame에서 제대로 적용이 되었는 지 확인 한다.

---

## ETC

---
* 기타사항을 작성한다.
* 기타사항을 작성한다.
* 기타사항을 작성한다.

**Comment by happy-baechuchu** [comment]
<img width="325" alt="image" src="https://github.com/MetaAir2023/WebRPG/assets/134986794/47671ce6-d91a-4d29-9617-f37733a21c44">
reboot.scss가 어디 있어요?? 여기를 수정해야 할 것 같은데..

**Comment by happy-baechuchu** [comment]
hover로 수정가능!!🤓
